name: Qa'id Jacobs - UX and Product Designer
title: Qa'id Jacobs - UX and Product Designer
description: The professional portfolio of Qa'id Jacobs
paginate: 10
baseurl: ''
collections:
- medium
- designs
